---------------------------------
[2024-01-15 13:26:15][INFO][200]:La conexion [dbconn_standard] esta desabilitada en el archivo .config
---------------------------------
[2024-01-15 13:26:15][INFO][200]:Iniciando ...
---------------------------------
[2024-01-15 13:26:15][INFO][200]:Se van a inferir 39 entidades
---------------------------------
[2024-01-15 13:26:17][EXCEPTION][500]:PYTHON-EXCEPTION:

>>>>>>>>>>>>>>>[TRACEBACK]<<<<<<<<<<<<<<<

  File "/Users/l03542515/Documents/demo_crowd/crowd-counting/src/inference/main.py", line 10, in <module>
    ProjectDirector.go( sys.argv )
  File "/Users/l03542515/Documents/demo_crowd/crowd-counting/src/inference/System/Director/ProjectDirector.py", line 143, in go
    ProjectDirector().setFlux( argv )
  File "/Users/l03542515/Documents/demo_crowd/crowd-counting/src/inference/System/Director/ProjectDirector.py", line 123, in setFlux
    asyncio.run(self.__play(
  File "/opt/anaconda3/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/l03542515/Documents/demo_crowd/crowd-counting/src/inference/System/Director/ProjectDirector.py", line 84, in __play
    person_entities = await infer.create_person_entities(camera_entities)
  File "/Users/l03542515/Documents/demo_crowd/crowd-counting/src/inference/System/App/InferProcedures/InferProcedures.py", line 77, in create_person_entities
    entities.append( await self.orion.infer(camera, decryptedF))
  File "/Users/l03542515/Documents/demo_crowd/crowd-counting/src/inference/System/App/OrionProcedures/OrionProcedures.py", line 60, in infer
    homography = await self.get_homography(camera)

>>>>>>>>>>>>>>[ERROR_DESC]<<<<<<<<<<<<<<<

  [AttributeError]:'OrionProcedures' object has no attribute 'get_homography'

>>>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<

