---------------------------------
[2024-01-14 17:41:00][INFO][200]:La conexion [dbconn_standard] esta desabilitada en el archivo .config
---------------------------------
[2024-01-14 17:41:00][INFO][200]:Iniciando ...
---------------------------------
[2024-01-14 17:41:00][INFO][200]:Se van a inferir 39 entidades
---------------------------------
[2024-01-14 17:41:19][EXCEPTION][500]:PYTHON-EXCEPTION:

>>>>>>>>>>>>>>>[TRACEBACK]<<<<<<<<<<<<<<<

  File "/Users/l03542515/Documents/demo_crowd/crowd-counting/src/inference/main.py", line 10, in <module>
    ProjectDirector.go( sys.argv )
  File "/Users/l03542515/Documents/demo_crowd/crowd-counting/src/inference/System/Director/ProjectDirector.py", line 141, in go
    ProjectDirector().setFlux( argv )
  File "/Users/l03542515/Documents/demo_crowd/crowd-counting/src/inference/System/Director/ProjectDirector.py", line 121, in setFlux
    asyncio.run(self.__play(
  File "/opt/anaconda3/envs/ultra/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/anaconda3/envs/ultra/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/opt/anaconda3/envs/ultra/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/opt/anaconda3/envs/ultra/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/opt/anaconda3/envs/ultra/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/l03542515/Documents/demo_crowd/crowd-counting/src/inference/System/Director/ProjectDirector.py", line 82, in __play
    person_entities = await infer.create_person_entities(camera_entities)
  File "/Users/l03542515/Documents/demo_crowd/crowd-counting/src/inference/System/App/InferProcedures/InferProcedures.py", line 59, in create_person_entities
    entities.append( await self.orion.infer(camera, decryptedF))
  File "/Users/l03542515/Documents/demo_crowd/crowd-counting/src/inference/System/App/OrionProcedures/OrionProcedures.py", line 105, in infer
    entities = self.track_video(filevideo, model, time)
  File "/Users/l03542515/Documents/demo_crowd/crowd-counting/src/inference/System/App/OrionProcedures/OrionProcedures.py", line 132, in track_video
    results = model.track(source=frame, persist=True, classes=0)
  File "/opt/anaconda3/envs/ultra/lib/python3.9/site-packages/ultralytics/yolo/engine/model.py", line 276, in track
    return self.predict(source=source, stream=stream, **kwargs)
  File "/opt/anaconda3/envs/ultra/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/anaconda3/envs/ultra/lib/python3.9/site-packages/ultralytics/yolo/engine/model.py", line 253, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/opt/anaconda3/envs/ultra/lib/python3.9/site-packages/ultralytics/yolo/engine/predictor.py", line 184, in __call__
    return list(self.stream_inference(source, model))  # merge list of Result into one
  File "/opt/anaconda3/envs/ultra/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/opt/anaconda3/envs/ultra/lib/python3.9/site-packages/ultralytics/yolo/engine/predictor.py", line 240, in stream_inference
    preds = self.model(im, augment=self.args.augment, visualize=visualize)
  File "/opt/anaconda3/envs/ultra/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/anaconda3/envs/ultra/lib/python3.9/site-packages/ultralytics/nn/autobackend.py", line 314, in forward
    y = self.model(im, augment=augment, visualize=visualize) if augment or visualize else self.model(im)
  File "/opt/anaconda3/envs/ultra/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/anaconda3/envs/ultra/lib/python3.9/site-packages/ultralytics/nn/tasks.py", line 213, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "/opt/anaconda3/envs/ultra/lib/python3.9/site-packages/ultralytics/nn/tasks.py", line 64, in _forward_once
    x = m(x)  # run
  File "/opt/anaconda3/envs/ultra/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/anaconda3/envs/ultra/lib/python3.9/site-packages/ultralytics/nn/modules/head.py", line 47, in forward
    x[i] = torch.cat((self.cv2[i](x[i]), self.cv3[i](x[i])), 1)
  File "/opt/anaconda3/envs/ultra/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/anaconda3/envs/ultra/lib/python3.9/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/opt/anaconda3/envs/ultra/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/anaconda3/envs/ultra/lib/python3.9/site-packages/ultralytics/nn/modules/conv.py", line 43, in forward_fuse
    return self.act(self.conv(x))
  File "/opt/anaconda3/envs/ultra/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/anaconda3/envs/ultra/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/opt/anaconda3/envs/ultra/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,

>>>>>>>>>>>>>>[ERROR_DESC]<<<<<<<<<<<<<<<

  [KeyboardInterrupt]:

>>>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<

