---------------------------------
[2024-01-04 22:08:49][INFO][200]:La conexion [dbconn_standard] esta desabilitada en el archivo .config
---------------------------------
[2024-01-04 22:08:49][INFO][200]:Iniciando ...
---------------------------------
[2024-01-04 22:08:54][EXCEPTION][500]:PYTHON-EXCEPTION:

>>>>>>>>>>>>>>>[TRACEBACK]<<<<<<<<<<<<<<<

  File "/home/alanromero/crowd-counting/src/inference/main.py", line 10, in <module>
    ProjectDirector.go( sys.argv )
  File "/home/alanromero/crowd-counting/src/inference/System/Director/ProjectDirector.py", line 141, in go
    ProjectDirector().setFlux( argv )
  File "/home/alanromero/crowd-counting/src/inference/System/Director/ProjectDirector.py", line 121, in setFlux
    asyncio.run(self.__play(
  File "/home/alanromero/anaconda3/envs/infer/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/alanromero/anaconda3/envs/infer/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/alanromero/crowd-counting/src/inference/System/Director/ProjectDirector.py", line 77, in __play
    camera_entities = await self.orion.ent2infer()
  File "/home/alanromero/crowd-counting/src/inference/System/App/OrionProcedures/OrionProcedures.py", line 94, in ent2infer
    cam_e = await self.client.query(type="cameraObserved")
  File "/home/alanromero/anaconda3/envs/infer/lib/python3.10/site-packages/ngsildclient/api/asyn/client.py", line 459, in query
    count = await self.entities.count(type, q, gq, ctx=ctx)
  File "/home/alanromero/anaconda3/envs/infer/lib/python3.10/site-packages/ngsildclient/api/exceptions.py", line 203, in inner_function
    raise NgsiApiError("Error while requesting the broker API") from e

>>>>>>>>>>>>>>[ERROR_DESC]<<<<<<<<<<<<<<<

  [NgsiApiError]:Error while requesting the broker API

>>>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<

