---------------------------------
[2024-01-15 08:52:30][INFO][200]:La conexion [dbconn_standard] esta desabilitada en el archivo .config
---------------------------------
[2024-01-15 08:52:30][INFO][200]:Iniciando ...
---------------------------------
[2024-01-15 08:52:31][EXCEPTION][500]:PYTHON-EXCEPTION:

>>>>>>>>>>>>>>>[TRACEBACK]<<<<<<<<<<<<<<<

  File "/Users/l03542515/Documents/demo_crowd/crowd-counting/src/inference/main.py", line 10, in <module>
    ProjectDirector.go( sys.argv )
  File "/Users/l03542515/Documents/demo_crowd/crowd-counting/src/inference/System/Director/ProjectDirector.py", line 152, in go
    ProjectDirector().setFlux( argv )
  File "/Users/l03542515/Documents/demo_crowd/crowd-counting/src/inference/System/Director/ProjectDirector.py", line 132, in setFlux
    asyncio.run(self.__play(
  File "/opt/anaconda3/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/l03542515/Documents/demo_crowd/crowd-counting/src/inference/System/Director/ProjectDirector.py", line 85, in __play
    camera_entities = response.json() #self.orion.ent2infer()
  File "/opt/anaconda3/lib/python3.9/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)

>>>>>>>>>>>>>>[ERROR_DESC]<<<<<<<<<<<<<<<

  [JSONDecodeError]:Expecting value: line 1 column 1 (char 0)

>>>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<

